<a href="https://colab.research.google.com/github/chandan-source/Iris_flower_prediction/blob/main/iris_dataset_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                      IRIS  DATASET PREDICTION
                                      

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df=pd.read_csv("/content/Iris.csv")

In [4]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [6]:
df.shape

(150, 6)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [8]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [9]:
li=['Id']
df.drop(li,axis=1,inplace=True)

#cleaning of data


In [10]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

#to convert the value of species column into numeric


In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le_S=LabelEncoder()
df['Species']=le_S.fit_transform(df['Species'])

#class 0-> iris setosa ,class 1-> iris versicolor, class 2-> iris virginica

In [14]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

# splitting of the data for training and testing

In [15]:
X_train=df.iloc[0:125, 0:4].values
Y_train=df.iloc[0:125, 4].values
X_test=df.iloc[125:150, 0:4].values
Y_test=df.iloc[125:150, 4].values

In [ ]:
X_train.shape,Y_train.shape,X_test.shape

#scaling of feature in the range of -1 to 1

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df=sc.fit_transform(X_train,X_test)

In [18]:
df

array([[-0.75052486,  0.9608333 , -1.16939032, -1.16033713],
       [-1.00408055, -0.13301153, -1.16939032, -1.16033713],
       [-1.25763624,  0.3045264 , -1.22734979, -1.16033713],
       [-1.38441409,  0.08575743, -1.11143085, -1.16033713],
       [-0.8773027 ,  1.17960226, -1.16939032, -1.16033713],
       [-0.37019131,  1.83590916, -0.9955119 , -0.8830099 ],
       [-1.38441409,  0.74206433, -1.16939032, -1.02167352],
       [-0.8773027 ,  0.74206433, -1.11143085, -1.16033713],
       [-1.63796979, -0.3517805 , -1.16939032, -1.16033713],
       [-1.00408055,  0.08575743, -1.11143085, -1.29900075],
       [-0.37019131,  1.39837123, -1.11143085, -1.16033713],
       [-1.1308584 ,  0.74206433, -1.05347137, -1.16033713],
       [-1.1308584 , -0.13301153, -1.16939032, -1.29900075],
       [-1.76474763, -0.13301153, -1.34326874, -1.29900075],
       [ 0.13692007,  2.05467812, -1.28530926, -1.16033713],
       [ 0.01014223,  2.92975398, -1.11143085, -0.8830099 ],
       [-0.37019131,  1.

# by using decision tree classification

In [ ]:
from sklearn.tree import DecisionTreeClassifier


In [ ]:
dt=DecisionTreeClassifier(criterion='entropy',max_depth=10)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10)

In [ ]:
dt.score(X_train,Y_train)

1.0

#traning accuracy 100%

In [ ]:
y_predict=dt.predict(X_train)

In [ ]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#testing accuracy 80%

In [ ]:
dt.score(X_test,Y_test)

0.8

#by using knn classification

In [ ]:
# by knn classfication
from sklearn.neighbors import KNeighborsClassifier
KN=KNeighborsClassifier(n_neighbors=7,n_jobs=-1)



In [ ]:
KN.fit(X_train,Y_train)

KNeighborsClassifier(n_jobs=-1, n_neighbors=7)

#traning score 97.6%

In [ ]:
KN.score(X_train,Y_train)

0.976

In [ ]:
y_predict=KN.predict(X_train)

In [ ]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2])

#testing score 84%

In [ ]:
KN.score(X_test,Y_test)

0.84

#by using randam forest for classfication

In [ ]:
# by random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(criterion='entropy',max_depth=10,n_jobs=-1,n_estimators=110)

In [ ]:
rf.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=110,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
y_predict=rf.predict(X_train)

In [ ]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#training score 100%

In [ ]:
rf.score(X_train,Y_train)

1.0

#testing score 80%

In [ ]:
rf.score(X_test,Y_test)

0.8